### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by marcuspoehls** [superchargejs/framework#1]
Keep a changelog a la [keepachangelog.com](https://keepachangelog.com/)

**Comment by ashwin-sureshkumar** [comment]
@marcuspoehls - suggestion to follow a standard commit messages to bring consistency and meaningful messages

Can use Commitzen and linting to validate messages. 
https://github.com/commitizen/cz-cli

Standard version auto generates changelog and versioning 
https://github.com/conventional-changelog/standard-version

Thoughts on the above?

**Comment by marcuspoehls** [comment]
@ashwin-sureshkumar Hey Ashwin, thank you for your ideas.

I’m not a fan of commit message guidelines. My guess is that commit messages will mostly be ignored by anyone. I propose to not put commit guidelines in place at this early stage.

More important is the changelog. I thought about manually maintaining a changelog in the format of [keepachangelog.com](https://keepachangelog.com). I never heard of `standard-version` and it looks nice. To automatically generate a changelog with `standard-version`, we would need to add commit guidelines.

Now I see your ideas are connected.

Ashwin, do you have experience with `commitizen` and `standard-version` in a project? Does it put more burden on the developer? Is it still enjoyable to contribute when worrying about the commit each time?

**Comment by ashwin-sureshkumar** [comment]
@marcuspoehls yes I do have experience I don't think it adds much of a burden. RxJS, Angular and many open source do follow commit guidelines. 

Commit messages are similar to any documentation. Its conveys what changes have been made in this particular commit. This helps with generating a change log without actually going through each commit and seeing what was done. We can still edit the change log to make it short and concise when needed.
